plugins {
    id "wtmp.deps-conventions"
    id "wtmp.java-conventions"
    id "wtmp.publishing-conventions"
    id "wtmp.versioning-conventions"
}

allprojects {
    group = 'gov.usbr'
    version = versionConventions.getConventionVersion()
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = "usbr-jasper-fonts"
            from components.java
        }
    }
}